// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package com_sangfor_moa_protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PB_EntryIpType int32

const (
	PB_EntryIpType_PBEIT_SECOND PB_EntryIpType = 0
	PB_EntryIpType_PBEIT_MASTER PB_EntryIpType = 1
)

var PB_EntryIpType_name = map[int32]string{
	0: "PBEIT_SECOND",
	1: "PBEIT_MASTER",
}
var PB_EntryIpType_value = map[string]int32{
	"PBEIT_SECOND": 0,
	"PBEIT_MASTER": 1,
}

func (x PB_EntryIpType) Enum() *PB_EntryIpType {
	p := new(PB_EntryIpType)
	*p = x
	return p
}
func (x PB_EntryIpType) String() string {
	return proto.EnumName(PB_EntryIpType_name, int32(x))
}
func (x *PB_EntryIpType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PB_EntryIpType_value, data, "PB_EntryIpType")
	if err != nil {
		return err
	}
	*x = PB_EntryIpType(value)
	return nil
}
func (PB_EntryIpType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type PB_AthAlgorithm int32

const (
	PB_AthAlgorithm_PBALGO_NONE PB_AthAlgorithm = 0
	PB_AthAlgorithm_PBALGO_AES  PB_AthAlgorithm = 1
)

var PB_AthAlgorithm_name = map[int32]string{
	0: "PBALGO_NONE",
	1: "PBALGO_AES",
}
var PB_AthAlgorithm_value = map[string]int32{
	"PBALGO_NONE": 0,
	"PBALGO_AES":  1,
}

func (x PB_AthAlgorithm) Enum() *PB_AthAlgorithm {
	p := new(PB_AthAlgorithm)
	*p = x
	return p
}
func (x PB_AthAlgorithm) String() string {
	return proto.EnumName(PB_AthAlgorithm_name, int32(x))
}
func (x *PB_AthAlgorithm) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PB_AthAlgorithm_value, data, "PB_AthAlgorithm")
	if err != nil {
		return err
	}
	*x = PB_AthAlgorithm(value)
	return nil
}
func (PB_AthAlgorithm) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type PB_AthUpdateType int32

const (
	PB_AthUpdateType_PBUPDATE_ORDINARY  PB_AthUpdateType = 0
	PB_AthUpdateType_PBUPDATE_EMERGENCY PB_AthUpdateType = 1
)

var PB_AthUpdateType_name = map[int32]string{
	0: "PBUPDATE_ORDINARY",
	1: "PBUPDATE_EMERGENCY",
}
var PB_AthUpdateType_value = map[string]int32{
	"PBUPDATE_ORDINARY":  0,
	"PBUPDATE_EMERGENCY": 1,
}

func (x PB_AthUpdateType) Enum() *PB_AthUpdateType {
	p := new(PB_AthUpdateType)
	*p = x
	return p
}
func (x PB_AthUpdateType) String() string {
	return proto.EnumName(PB_AthUpdateType_name, int32(x))
}
func (x *PB_AthUpdateType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PB_AthUpdateType_value, data, "PB_AthUpdateType")
	if err != nil {
		return err
	}
	*x = PB_AthUpdateType(value)
	return nil
}
func (PB_AthUpdateType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type PB_AthWebStatus int32

const (
	PB_AthWebStatus_AWS_OFFLINE PB_AthWebStatus = 0
	PB_AthWebStatus_AWS_ONLINE  PB_AthWebStatus = 1
)

var PB_AthWebStatus_name = map[int32]string{
	0: "AWS_OFFLINE",
	1: "AWS_ONLINE",
}
var PB_AthWebStatus_value = map[string]int32{
	"AWS_OFFLINE": 0,
	"AWS_ONLINE":  1,
}

func (x PB_AthWebStatus) Enum() *PB_AthWebStatus {
	p := new(PB_AthWebStatus)
	*p = x
	return p
}
func (x PB_AthWebStatus) String() string {
	return proto.EnumName(PB_AthWebStatus_name, int32(x))
}
func (x *PB_AthWebStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PB_AthWebStatus_value, data, "PB_AthWebStatus")
	if err != nil {
		return err
	}
	*x = PB_AthWebStatus(value)
	return nil
}
func (PB_AthWebStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type PB_AthVersionChange int32

const (
	PB_AthVersionChange_VERSION_CHANGED   PB_AthVersionChange = 0
	PB_AthVersionChange_VERSION_UNCHANGED PB_AthVersionChange = 1
)

var PB_AthVersionChange_name = map[int32]string{
	0: "VERSION_CHANGED",
	1: "VERSION_UNCHANGED",
}
var PB_AthVersionChange_value = map[string]int32{
	"VERSION_CHANGED":   0,
	"VERSION_UNCHANGED": 1,
}

func (x PB_AthVersionChange) Enum() *PB_AthVersionChange {
	p := new(PB_AthVersionChange)
	*p = x
	return p
}
func (x PB_AthVersionChange) String() string {
	return proto.EnumName(PB_AthVersionChange_name, int32(x))
}
func (x *PB_AthVersionChange) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PB_AthVersionChange_value, data, "PB_AthVersionChange")
	if err != nil {
		return err
	}
	*x = PB_AthVersionChange(value)
	return nil
}
func (PB_AthVersionChange) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type PB_EntryIp struct {
	Type             *int32  `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Ip               *string `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PB_EntryIp) Reset()                    { *m = PB_EntryIp{} }
func (m *PB_EntryIp) String() string            { return proto.CompactTextString(m) }
func (*PB_EntryIp) ProtoMessage()               {}
func (*PB_EntryIp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *PB_EntryIp) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *PB_EntryIp) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

type PB_EntryIpPool struct {
	Version          *int32        `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Ips              []*PB_EntryIp `protobuf:"bytes,2,rep,name=ips" json:"ips,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PB_EntryIpPool) Reset()                    { *m = PB_EntryIpPool{} }
func (m *PB_EntryIpPool) String() string            { return proto.CompactTextString(m) }
func (*PB_EntryIpPool) ProtoMessage()               {}
func (*PB_EntryIpPool) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *PB_EntryIpPool) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *PB_EntryIpPool) GetIps() []*PB_EntryIp {
	if m != nil {
		return m.Ips
	}
	return nil
}

type PB_AthLoginReq struct {
	DomainName        *string           `protobuf:"bytes,1,req,name=domain_name,json=domainName" json:"domain_name,omitempty"`
	LoginAccount      *string           `protobuf:"bytes,2,req,name=login_account,json=loginAccount" json:"login_account,omitempty"`
	ClientVersion     *string           `protobuf:"bytes,3,req,name=client_version,json=clientVersion" json:"client_version,omitempty"`
	Cdt               *PB_ClientDevType `protobuf:"varint,4,opt,name=cdt,enum=com.sangfor.moa.protobuf.PB_ClientDevType,def=0" json:"cdt,omitempty"`
	Did               *int64            `protobuf:"varint,5,opt,name=did" json:"did,omitempty"`
	UniqueCode        *string           `protobuf:"bytes,6,opt,name=unique_code,json=uniqueCode" json:"unique_code,omitempty"`
	DeviceInfo        *string           `protobuf:"bytes,7,opt,name=device_info,json=deviceInfo" json:"device_info,omitempty"`
	IpPoolVer         *int32            `protobuf:"varint,8,opt,name=ip_pool_ver,json=ipPoolVer" json:"ip_pool_ver,omitempty"`
	AndroidUniqueFlag *string           `protobuf:"bytes,9,opt,name=android_unique_flag,json=androidUniqueFlag" json:"android_unique_flag,omitempty"`
	ClientSystem      *string           `protobuf:"bytes,10,opt,name=client_system,json=clientSystem" json:"client_system,omitempty"`
	XXX_unrecognized  []byte            `json:"-"`
}

func (m *PB_AthLoginReq) Reset()                    { *m = PB_AthLoginReq{} }
func (m *PB_AthLoginReq) String() string            { return proto.CompactTextString(m) }
func (*PB_AthLoginReq) ProtoMessage()               {}
func (*PB_AthLoginReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

const Default_PB_AthLoginReq_Cdt PB_ClientDevType = PB_ClientDevType_PBCDT_ANDROID

func (m *PB_AthLoginReq) GetDomainName() string {
	if m != nil && m.DomainName != nil {
		return *m.DomainName
	}
	return ""
}

func (m *PB_AthLoginReq) GetLoginAccount() string {
	if m != nil && m.LoginAccount != nil {
		return *m.LoginAccount
	}
	return ""
}

func (m *PB_AthLoginReq) GetClientVersion() string {
	if m != nil && m.ClientVersion != nil {
		return *m.ClientVersion
	}
	return ""
}

func (m *PB_AthLoginReq) GetCdt() PB_ClientDevType {
	if m != nil && m.Cdt != nil {
		return *m.Cdt
	}
	return Default_PB_AthLoginReq_Cdt
}

func (m *PB_AthLoginReq) GetDid() int64 {
	if m != nil && m.Did != nil {
		return *m.Did
	}
	return 0
}

func (m *PB_AthLoginReq) GetUniqueCode() string {
	if m != nil && m.UniqueCode != nil {
		return *m.UniqueCode
	}
	return ""
}

func (m *PB_AthLoginReq) GetDeviceInfo() string {
	if m != nil && m.DeviceInfo != nil {
		return *m.DeviceInfo
	}
	return ""
}

func (m *PB_AthLoginReq) GetIpPoolVer() int32 {
	if m != nil && m.IpPoolVer != nil {
		return *m.IpPoolVer
	}
	return 0
}

func (m *PB_AthLoginReq) GetAndroidUniqueFlag() string {
	if m != nil && m.AndroidUniqueFlag != nil {
		return *m.AndroidUniqueFlag
	}
	return ""
}

func (m *PB_AthLoginReq) GetClientSystem() string {
	if m != nil && m.ClientSystem != nil {
		return *m.ClientSystem
	}
	return ""
}

type PB_AthLoginRsp struct {
	Result           *int32           `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	ServerVersion    *string          `protobuf:"bytes,2,opt,name=server_version,json=serverVersion" json:"server_version,omitempty"`
	AuthSeed         []byte           `protobuf:"bytes,3,opt,name=auth_seed,json=authSeed" json:"auth_seed,omitempty"`
	AuthAlgo         *PB_AthAlgorithm `protobuf:"varint,4,opt,name=auth_algo,json=authAlgo,enum=com.sangfor.moa.protobuf.PB_AthAlgorithm,def=0" json:"auth_algo,omitempty"`
	LatestClientVer  *string          `protobuf:"bytes,5,opt,name=latest_client_ver,json=latestClientVer" json:"latest_client_ver,omitempty"`
	UpdateUrl        *string          `protobuf:"bytes,6,opt,name=update_url,json=updateUrl" json:"update_url,omitempty"`
	UpdateInfo       []string         `protobuf:"bytes,7,rep,name=update_info,json=updateInfo" json:"update_info,omitempty"`
	Ips              []string         `protobuf:"bytes,8,rep,name=ips" json:"ips,omitempty"`
	UpdateType       *int32           `protobuf:"varint,9,opt,name=update_type,json=updateType" json:"update_type,omitempty"`
	IpPool           *PB_EntryIpPool  `protobuf:"bytes,10,opt,name=ip_pool,json=ipPool" json:"ip_pool,omitempty"`
	NeedCaptcha      *int32           `protobuf:"varint,11,opt,name=need_captcha,json=needCaptcha" json:"need_captcha,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *PB_AthLoginRsp) Reset()                    { *m = PB_AthLoginRsp{} }
func (m *PB_AthLoginRsp) String() string            { return proto.CompactTextString(m) }
func (*PB_AthLoginRsp) ProtoMessage()               {}
func (*PB_AthLoginRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

const Default_PB_AthLoginRsp_AuthAlgo PB_AthAlgorithm = PB_AthAlgorithm_PBALGO_NONE

func (m *PB_AthLoginRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *PB_AthLoginRsp) GetServerVersion() string {
	if m != nil && m.ServerVersion != nil {
		return *m.ServerVersion
	}
	return ""
}

func (m *PB_AthLoginRsp) GetAuthSeed() []byte {
	if m != nil {
		return m.AuthSeed
	}
	return nil
}

func (m *PB_AthLoginRsp) GetAuthAlgo() PB_AthAlgorithm {
	if m != nil && m.AuthAlgo != nil {
		return *m.AuthAlgo
	}
	return Default_PB_AthLoginRsp_AuthAlgo
}

func (m *PB_AthLoginRsp) GetLatestClientVer() string {
	if m != nil && m.LatestClientVer != nil {
		return *m.LatestClientVer
	}
	return ""
}

func (m *PB_AthLoginRsp) GetUpdateUrl() string {
	if m != nil && m.UpdateUrl != nil {
		return *m.UpdateUrl
	}
	return ""
}

func (m *PB_AthLoginRsp) GetUpdateInfo() []string {
	if m != nil {
		return m.UpdateInfo
	}
	return nil
}

func (m *PB_AthLoginRsp) GetIps() []string {
	if m != nil {
		return m.Ips
	}
	return nil
}

func (m *PB_AthLoginRsp) GetUpdateType() int32 {
	if m != nil && m.UpdateType != nil {
		return *m.UpdateType
	}
	return 0
}

func (m *PB_AthLoginRsp) GetIpPool() *PB_EntryIpPool {
	if m != nil {
		return m.IpPool
	}
	return nil
}

func (m *PB_AthLoginRsp) GetNeedCaptcha() int32 {
	if m != nil && m.NeedCaptcha != nil {
		return *m.NeedCaptcha
	}
	return 0
}

type PB_AthAuthReq struct {
	// optional string domain_name = 1;	//	登录域名。这个消息中客户端不用设置这个字段，后台交互使用(该字段已废弃--2014-06-03)
	LoginAccount     *string `protobuf:"bytes,2,opt,name=login_account,json=loginAccount" json:"login_account,omitempty"`
	EncryptData      []byte  `protobuf:"bytes,3,opt,name=encrypt_data,json=encryptData" json:"encrypt_data,omitempty"`
	Did              *int64  `protobuf:"varint,4,opt,name=did" json:"did,omitempty"`
	WebNonce         []byte  `protobuf:"bytes,6,opt,name=web_nonce,json=webNonce" json:"web_nonce,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PB_AthAuthReq) Reset()                    { *m = PB_AthAuthReq{} }
func (m *PB_AthAuthReq) String() string            { return proto.CompactTextString(m) }
func (*PB_AthAuthReq) ProtoMessage()               {}
func (*PB_AthAuthReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *PB_AthAuthReq) GetLoginAccount() string {
	if m != nil && m.LoginAccount != nil {
		return *m.LoginAccount
	}
	return ""
}

func (m *PB_AthAuthReq) GetEncryptData() []byte {
	if m != nil {
		return m.EncryptData
	}
	return nil
}

func (m *PB_AthAuthReq) GetDid() int64 {
	if m != nil && m.Did != nil {
		return *m.Did
	}
	return 0
}

func (m *PB_AthAuthReq) GetWebNonce() []byte {
	if m != nil {
		return m.WebNonce
	}
	return nil
}

type PB_AthAuthRsp struct {
	Result      *int32           `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Did         *int64           `protobuf:"varint,2,opt,name=did" json:"did,omitempty"`
	Pid         *int64           `protobuf:"varint,3,opt,name=pid" json:"pid,omitempty"`
	Ticket      []byte           `protobuf:"bytes,4,opt,name=ticket" json:"ticket,omitempty"`
	WebStatus   *PB_AthWebStatus `protobuf:"varint,5,opt,name=web_status,json=webStatus,enum=com.sangfor.moa.protobuf.PB_AthWebStatus" json:"web_status,omitempty"`
	DomainName  *string          `protobuf:"bytes,6,opt,name=domain_name,json=domainName" json:"domain_name,omitempty"`
	Ptype       *PB_PidType      `protobuf:"varint,7,opt,name=ptype,enum=com.sangfor.moa.protobuf.PB_PidType" json:"ptype,omitempty"`
	ServerTime  *int64           `protobuf:"varint,8,opt,name=server_time,json=serverTime" json:"server_time,omitempty"`
	SheetStatus *uint32          `protobuf:"varint,9,opt,name=sheet_status,json=sheetStatus" json:"sheet_status,omitempty"`
	// 所以客户端用sheet_status位与0x00000001如果是0x00000001，则不需要强制设置密码,(2104-10-11)
	Ips []string `protobuf:"bytes,10,rep,name=ips" json:"ips,omitempty"`
	// srv	optional int32 captcha = 11;									//  返回验证码
	IsPrivateCloud   *int32 `protobuf:"varint,12,opt,name=is_private_cloud,json=isPrivateCloud" json:"is_private_cloud,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PB_AthAuthRsp) Reset()                    { *m = PB_AthAuthRsp{} }
func (m *PB_AthAuthRsp) String() string            { return proto.CompactTextString(m) }
func (*PB_AthAuthRsp) ProtoMessage()               {}
func (*PB_AthAuthRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *PB_AthAuthRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *PB_AthAuthRsp) GetDid() int64 {
	if m != nil && m.Did != nil {
		return *m.Did
	}
	return 0
}

func (m *PB_AthAuthRsp) GetPid() int64 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

func (m *PB_AthAuthRsp) GetTicket() []byte {
	if m != nil {
		return m.Ticket
	}
	return nil
}

func (m *PB_AthAuthRsp) GetWebStatus() PB_AthWebStatus {
	if m != nil && m.WebStatus != nil {
		return *m.WebStatus
	}
	return PB_AthWebStatus_AWS_OFFLINE
}

func (m *PB_AthAuthRsp) GetDomainName() string {
	if m != nil && m.DomainName != nil {
		return *m.DomainName
	}
	return ""
}

func (m *PB_AthAuthRsp) GetPtype() PB_PidType {
	if m != nil && m.Ptype != nil {
		return *m.Ptype
	}
	return PB_PidType_PID_PERSONAL
}

func (m *PB_AthAuthRsp) GetServerTime() int64 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

func (m *PB_AthAuthRsp) GetSheetStatus() uint32 {
	if m != nil && m.SheetStatus != nil {
		return *m.SheetStatus
	}
	return 0
}

func (m *PB_AthAuthRsp) GetIps() []string {
	if m != nil {
		return m.Ips
	}
	return nil
}

func (m *PB_AthAuthRsp) GetIsPrivateCloud() int32 {
	if m != nil && m.IsPrivateCloud != nil {
		return *m.IsPrivateCloud
	}
	return 0
}

// 【短信验证，也需要经过login才进行这里】
type PB_AthAuthCaptchaReq struct {
	LoginAccount     *string `protobuf:"bytes,1,opt,name=login_account,json=loginAccount" json:"login_account,omitempty"`
	Captcha          *string `protobuf:"bytes,2,opt,name=captcha" json:"captcha,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PB_AthAuthCaptchaReq) Reset()                    { *m = PB_AthAuthCaptchaReq{} }
func (m *PB_AthAuthCaptchaReq) String() string            { return proto.CompactTextString(m) }
func (*PB_AthAuthCaptchaReq) ProtoMessage()               {}
func (*PB_AthAuthCaptchaReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *PB_AthAuthCaptchaReq) GetLoginAccount() string {
	if m != nil && m.LoginAccount != nil {
		return *m.LoginAccount
	}
	return ""
}

func (m *PB_AthAuthCaptchaReq) GetCaptcha() string {
	if m != nil && m.Captcha != nil {
		return *m.Captcha
	}
	return ""
}

type PB_AthAuthCaptchaRsp struct {
	Result      *int32           `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Did         *int64           `protobuf:"varint,2,opt,name=did" json:"did,omitempty"`
	Pid         *int64           `protobuf:"varint,3,opt,name=pid" json:"pid,omitempty"`
	Ticket      []byte           `protobuf:"bytes,4,opt,name=ticket" json:"ticket,omitempty"`
	WebStatus   *PB_AthWebStatus `protobuf:"varint,5,opt,name=web_status,json=webStatus,enum=com.sangfor.moa.protobuf.PB_AthWebStatus" json:"web_status,omitempty"`
	DomainName  *string          `protobuf:"bytes,6,opt,name=domain_name,json=domainName" json:"domain_name,omitempty"`
	Ptype       *PB_PidType      `protobuf:"varint,7,opt,name=ptype,enum=com.sangfor.moa.protobuf.PB_PidType" json:"ptype,omitempty"`
	ServerTime  *int64           `protobuf:"varint,8,opt,name=server_time,json=serverTime" json:"server_time,omitempty"`
	SheetStatus *uint32          `protobuf:"varint,9,opt,name=sheet_status,json=sheetStatus" json:"sheet_status,omitempty"`
	// 所以客户端用sheet_status位与0x00000001如果是0x00000001，则不需要强制设置密码,(2104-10-11)
	Ips              []string `protobuf:"bytes,10,rep,name=ips" json:"ips,omitempty"`
	IsPrivateCloud   *int32   `protobuf:"varint,11,opt,name=is_private_cloud,json=isPrivateCloud" json:"is_private_cloud,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PB_AthAuthCaptchaRsp) Reset()                    { *m = PB_AthAuthCaptchaRsp{} }
func (m *PB_AthAuthCaptchaRsp) String() string            { return proto.CompactTextString(m) }
func (*PB_AthAuthCaptchaRsp) ProtoMessage()               {}
func (*PB_AthAuthCaptchaRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *PB_AthAuthCaptchaRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *PB_AthAuthCaptchaRsp) GetDid() int64 {
	if m != nil && m.Did != nil {
		return *m.Did
	}
	return 0
}

func (m *PB_AthAuthCaptchaRsp) GetPid() int64 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

func (m *PB_AthAuthCaptchaRsp) GetTicket() []byte {
	if m != nil {
		return m.Ticket
	}
	return nil
}

func (m *PB_AthAuthCaptchaRsp) GetWebStatus() PB_AthWebStatus {
	if m != nil && m.WebStatus != nil {
		return *m.WebStatus
	}
	return PB_AthWebStatus_AWS_OFFLINE
}

func (m *PB_AthAuthCaptchaRsp) GetDomainName() string {
	if m != nil && m.DomainName != nil {
		return *m.DomainName
	}
	return ""
}

func (m *PB_AthAuthCaptchaRsp) GetPtype() PB_PidType {
	if m != nil && m.Ptype != nil {
		return *m.Ptype
	}
	return PB_PidType_PID_PERSONAL
}

func (m *PB_AthAuthCaptchaRsp) GetServerTime() int64 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

func (m *PB_AthAuthCaptchaRsp) GetSheetStatus() uint32 {
	if m != nil && m.SheetStatus != nil {
		return *m.SheetStatus
	}
	return 0
}

func (m *PB_AthAuthCaptchaRsp) GetIps() []string {
	if m != nil {
		return m.Ips
	}
	return nil
}

func (m *PB_AthAuthCaptchaRsp) GetIsPrivateCloud() int32 {
	if m != nil && m.IsPrivateCloud != nil {
		return *m.IsPrivateCloud
	}
	return 0
}

// 获取选择公司的密码，填写 login_account 和 did
type PB_AthFindPasswordReq struct {
	LoginAccount     *string `protobuf:"bytes,1,req,name=login_account,json=loginAccount" json:"login_account,omitempty"`
	Did              *int64  `protobuf:"varint,2,opt,name=did" json:"did,omitempty"`
	Captcha          *string `protobuf:"bytes,3,opt,name=captcha" json:"captcha,omitempty"`
	NewPassword      []byte  `protobuf:"bytes,4,opt,name=new_password,json=newPassword" json:"new_password,omitempty"`
	UniqueCode       *string `protobuf:"bytes,5,opt,name=unique_code,json=uniqueCode" json:"unique_code,omitempty"`
	IncCaptcha       *int32  `protobuf:"varint,6,opt,name=inc_captcha,json=incCaptcha" json:"inc_captcha,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PB_AthFindPasswordReq) Reset()                    { *m = PB_AthFindPasswordReq{} }
func (m *PB_AthFindPasswordReq) String() string            { return proto.CompactTextString(m) }
func (*PB_AthFindPasswordReq) ProtoMessage()               {}
func (*PB_AthFindPasswordReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *PB_AthFindPasswordReq) GetLoginAccount() string {
	if m != nil && m.LoginAccount != nil {
		return *m.LoginAccount
	}
	return ""
}

func (m *PB_AthFindPasswordReq) GetDid() int64 {
	if m != nil && m.Did != nil {
		return *m.Did
	}
	return 0
}

func (m *PB_AthFindPasswordReq) GetCaptcha() string {
	if m != nil && m.Captcha != nil {
		return *m.Captcha
	}
	return ""
}

func (m *PB_AthFindPasswordReq) GetNewPassword() []byte {
	if m != nil {
		return m.NewPassword
	}
	return nil
}

func (m *PB_AthFindPasswordReq) GetUniqueCode() string {
	if m != nil && m.UniqueCode != nil {
		return *m.UniqueCode
	}
	return ""
}

func (m *PB_AthFindPasswordReq) GetIncCaptcha() int32 {
	if m != nil && m.IncCaptcha != nil {
		return *m.IncCaptcha
	}
	return 0
}

type PB_AthFindPasswordDomainInfo struct {
	Did              *int64  `protobuf:"varint,1,req,name=did" json:"did,omitempty"`
	Dname            *string `protobuf:"bytes,2,opt,name=dname" json:"dname,omitempty"`
	AdminPid         *int64  `protobuf:"varint,3,opt,name=admin_pid,json=adminPid" json:"admin_pid,omitempty"`
	AdminName        *string `protobuf:"bytes,4,opt,name=admin_name,json=adminName" json:"admin_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PB_AthFindPasswordDomainInfo) Reset()                    { *m = PB_AthFindPasswordDomainInfo{} }
func (m *PB_AthFindPasswordDomainInfo) String() string            { return proto.CompactTextString(m) }
func (*PB_AthFindPasswordDomainInfo) ProtoMessage()               {}
func (*PB_AthFindPasswordDomainInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *PB_AthFindPasswordDomainInfo) GetDid() int64 {
	if m != nil && m.Did != nil {
		return *m.Did
	}
	return 0
}

func (m *PB_AthFindPasswordDomainInfo) GetDname() string {
	if m != nil && m.Dname != nil {
		return *m.Dname
	}
	return ""
}

func (m *PB_AthFindPasswordDomainInfo) GetAdminPid() int64 {
	if m != nil && m.AdminPid != nil {
		return *m.AdminPid
	}
	return 0
}

func (m *PB_AthFindPasswordDomainInfo) GetAdminName() string {
	if m != nil && m.AdminName != nil {
		return *m.AdminName
	}
	return ""
}

type PB_AthFindPasswordRsp struct {
	Result           *int32                          `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Domains          []*PB_AthFindPasswordDomainInfo `protobuf:"bytes,2,rep,name=domains" json:"domains,omitempty"`
	Ips              []string                        `protobuf:"bytes,3,rep,name=ips" json:"ips,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *PB_AthFindPasswordRsp) Reset()                    { *m = PB_AthFindPasswordRsp{} }
func (m *PB_AthFindPasswordRsp) String() string            { return proto.CompactTextString(m) }
func (*PB_AthFindPasswordRsp) ProtoMessage()               {}
func (*PB_AthFindPasswordRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *PB_AthFindPasswordRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *PB_AthFindPasswordRsp) GetDomains() []*PB_AthFindPasswordDomainInfo {
	if m != nil {
		return m.Domains
	}
	return nil
}

func (m *PB_AthFindPasswordRsp) GetIps() []string {
	if m != nil {
		return m.Ips
	}
	return nil
}

type PB_AthModifyPasswordReq struct {
	Did              *int64 `protobuf:"varint,1,opt,name=did" json:"did,omitempty"`
	Pid              *int64 `protobuf:"varint,2,opt,name=pid" json:"pid,omitempty"`
	OldPassword      []byte `protobuf:"bytes,3,req,name=old_password,json=oldPassword" json:"old_password,omitempty"`
	NewPassword      []byte `protobuf:"bytes,4,req,name=new_password,json=newPassword" json:"new_password,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PB_AthModifyPasswordReq) Reset()                    { *m = PB_AthModifyPasswordReq{} }
func (m *PB_AthModifyPasswordReq) String() string            { return proto.CompactTextString(m) }
func (*PB_AthModifyPasswordReq) ProtoMessage()               {}
func (*PB_AthModifyPasswordReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *PB_AthModifyPasswordReq) GetDid() int64 {
	if m != nil && m.Did != nil {
		return *m.Did
	}
	return 0
}

func (m *PB_AthModifyPasswordReq) GetPid() int64 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

func (m *PB_AthModifyPasswordReq) GetOldPassword() []byte {
	if m != nil {
		return m.OldPassword
	}
	return nil
}

func (m *PB_AthModifyPasswordReq) GetNewPassword() []byte {
	if m != nil {
		return m.NewPassword
	}
	return nil
}

type PB_AthModifyPasswordRsp struct {
	Result           *int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PB_AthModifyPasswordRsp) Reset()                    { *m = PB_AthModifyPasswordRsp{} }
func (m *PB_AthModifyPasswordRsp) String() string            { return proto.CompactTextString(m) }
func (*PB_AthModifyPasswordRsp) ProtoMessage()               {}
func (*PB_AthModifyPasswordRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *PB_AthModifyPasswordRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type PB_AthVerifyTicketReq struct {
	Did               *int64            `protobuf:"varint,1,req,name=did" json:"did,omitempty"`
	Pid               *int64            `protobuf:"varint,2,req,name=pid" json:"pid,omitempty"`
	Cdt               *PB_ClientDevType `protobuf:"varint,3,opt,name=cdt,enum=com.sangfor.moa.protobuf.PB_ClientDevType,def=0" json:"cdt,omitempty"`
	Ticket            []byte            `protobuf:"bytes,4,req,name=ticket" json:"ticket,omitempty"`
	ClientVersion     *string           `protobuf:"bytes,5,opt,name=client_version,json=clientVersion" json:"client_version,omitempty"`
	EncryptData       []byte            `protobuf:"bytes,6,opt,name=encrypt_data,json=encryptData" json:"encrypt_data,omitempty"`
	UniqueCode        *string           `protobuf:"bytes,7,opt,name=unique_code,json=uniqueCode" json:"unique_code,omitempty"`
	DeviceInfo        *string           `protobuf:"bytes,8,opt,name=device_info,json=deviceInfo" json:"device_info,omitempty"`
	IpPoolVer         *int32            `protobuf:"varint,9,opt,name=ip_pool_ver,json=ipPoolVer" json:"ip_pool_ver,omitempty"`
	AndroidUniqueFlag *string           `protobuf:"bytes,10,opt,name=android_unique_flag,json=androidUniqueFlag" json:"android_unique_flag,omitempty"`
	ClientSystem      *string           `protobuf:"bytes,11,opt,name=client_system,json=clientSystem" json:"client_system,omitempty"`
	XXX_unrecognized  []byte            `json:"-"`
}

func (m *PB_AthVerifyTicketReq) Reset()                    { *m = PB_AthVerifyTicketReq{} }
func (m *PB_AthVerifyTicketReq) String() string            { return proto.CompactTextString(m) }
func (*PB_AthVerifyTicketReq) ProtoMessage()               {}
func (*PB_AthVerifyTicketReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

const Default_PB_AthVerifyTicketReq_Cdt PB_ClientDevType = PB_ClientDevType_PBCDT_ANDROID

func (m *PB_AthVerifyTicketReq) GetDid() int64 {
	if m != nil && m.Did != nil {
		return *m.Did
	}
	return 0
}

func (m *PB_AthVerifyTicketReq) GetPid() int64 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

func (m *PB_AthVerifyTicketReq) GetCdt() PB_ClientDevType {
	if m != nil && m.Cdt != nil {
		return *m.Cdt
	}
	return Default_PB_AthVerifyTicketReq_Cdt
}

func (m *PB_AthVerifyTicketReq) GetTicket() []byte {
	if m != nil {
		return m.Ticket
	}
	return nil
}

func (m *PB_AthVerifyTicketReq) GetClientVersion() string {
	if m != nil && m.ClientVersion != nil {
		return *m.ClientVersion
	}
	return ""
}

func (m *PB_AthVerifyTicketReq) GetEncryptData() []byte {
	if m != nil {
		return m.EncryptData
	}
	return nil
}

func (m *PB_AthVerifyTicketReq) GetUniqueCode() string {
	if m != nil && m.UniqueCode != nil {
		return *m.UniqueCode
	}
	return ""
}

func (m *PB_AthVerifyTicketReq) GetDeviceInfo() string {
	if m != nil && m.DeviceInfo != nil {
		return *m.DeviceInfo
	}
	return ""
}

func (m *PB_AthVerifyTicketReq) GetIpPoolVer() int32 {
	if m != nil && m.IpPoolVer != nil {
		return *m.IpPoolVer
	}
	return 0
}

func (m *PB_AthVerifyTicketReq) GetAndroidUniqueFlag() string {
	if m != nil && m.AndroidUniqueFlag != nil {
		return *m.AndroidUniqueFlag
	}
	return ""
}

func (m *PB_AthVerifyTicketReq) GetClientSystem() string {
	if m != nil && m.ClientSystem != nil {
		return *m.ClientSystem
	}
	return ""
}

type PB_AthVerifyTicketRsp struct {
	Result           *int32           `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Did              *int64           `protobuf:"varint,2,opt,name=did" json:"did,omitempty"`
	Pid              *int64           `protobuf:"varint,3,opt,name=pid" json:"pid,omitempty"`
	DomainName       *string          `protobuf:"bytes,4,opt,name=domain_name,json=domainName" json:"domain_name,omitempty"`
	LoginAccount     *string          `protobuf:"bytes,5,opt,name=login_account,json=loginAccount" json:"login_account,omitempty"`
	Ticket           []byte           `protobuf:"bytes,6,opt,name=ticket" json:"ticket,omitempty"`
	LatestClientVer  *string          `protobuf:"bytes,7,opt,name=latest_client_ver,json=latestClientVer" json:"latest_client_ver,omitempty"`
	UpdateUrl        *string          `protobuf:"bytes,8,opt,name=update_url,json=updateUrl" json:"update_url,omitempty"`
	UpdateInfo       []string         `protobuf:"bytes,9,rep,name=update_info,json=updateInfo" json:"update_info,omitempty"`
	WebStatus        *PB_AthWebStatus `protobuf:"varint,10,opt,name=web_status,json=webStatus,enum=com.sangfor.moa.protobuf.PB_AthWebStatus" json:"web_status,omitempty"`
	Ptype            *PB_PidType      `protobuf:"varint,11,opt,name=ptype,enum=com.sangfor.moa.protobuf.PB_PidType" json:"ptype,omitempty"`
	ServerVersion    *string          `protobuf:"bytes,12,opt,name=server_version,json=serverVersion" json:"server_version,omitempty"`
	Ips              []string         `protobuf:"bytes,13,rep,name=ips" json:"ips,omitempty"`
	ServerTime       *int64           `protobuf:"varint,14,opt,name=server_time,json=serverTime" json:"server_time,omitempty"`
	SheetStatus      *uint32          `protobuf:"varint,15,opt,name=sheet_status,json=sheetStatus" json:"sheet_status,omitempty"`
	UpdateType       *int32           `protobuf:"varint,16,opt,name=update_type,json=updateType" json:"update_type,omitempty"`
	IpPool           *PB_EntryIpPool  `protobuf:"bytes,17,opt,name=ip_pool,json=ipPool" json:"ip_pool,omitempty"`
	IsPrivateCloud   *int32           `protobuf:"varint,18,opt,name=is_private_cloud,json=isPrivateCloud" json:"is_private_cloud,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *PB_AthVerifyTicketRsp) Reset()                    { *m = PB_AthVerifyTicketRsp{} }
func (m *PB_AthVerifyTicketRsp) String() string            { return proto.CompactTextString(m) }
func (*PB_AthVerifyTicketRsp) ProtoMessage()               {}
func (*PB_AthVerifyTicketRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *PB_AthVerifyTicketRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *PB_AthVerifyTicketRsp) GetDid() int64 {
	if m != nil && m.Did != nil {
		return *m.Did
	}
	return 0
}

func (m *PB_AthVerifyTicketRsp) GetPid() int64 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

func (m *PB_AthVerifyTicketRsp) GetDomainName() string {
	if m != nil && m.DomainName != nil {
		return *m.DomainName
	}
	return ""
}

func (m *PB_AthVerifyTicketRsp) GetLoginAccount() string {
	if m != nil && m.LoginAccount != nil {
		return *m.LoginAccount
	}
	return ""
}

func (m *PB_AthVerifyTicketRsp) GetTicket() []byte {
	if m != nil {
		return m.Ticket
	}
	return nil
}

func (m *PB_AthVerifyTicketRsp) GetLatestClientVer() string {
	if m != nil && m.LatestClientVer != nil {
		return *m.LatestClientVer
	}
	return ""
}

func (m *PB_AthVerifyTicketRsp) GetUpdateUrl() string {
	if m != nil && m.UpdateUrl != nil {
		return *m.UpdateUrl
	}
	return ""
}

func (m *PB_AthVerifyTicketRsp) GetUpdateInfo() []string {
	if m != nil {
		return m.UpdateInfo
	}
	return nil
}

func (m *PB_AthVerifyTicketRsp) GetWebStatus() PB_AthWebStatus {
	if m != nil && m.WebStatus != nil {
		return *m.WebStatus
	}
	return PB_AthWebStatus_AWS_OFFLINE
}

func (m *PB_AthVerifyTicketRsp) GetPtype() PB_PidType {
	if m != nil && m.Ptype != nil {
		return *m.Ptype
	}
	return PB_PidType_PID_PERSONAL
}

func (m *PB_AthVerifyTicketRsp) GetServerVersion() string {
	if m != nil && m.ServerVersion != nil {
		return *m.ServerVersion
	}
	return ""
}

func (m *PB_AthVerifyTicketRsp) GetIps() []string {
	if m != nil {
		return m.Ips
	}
	return nil
}

func (m *PB_AthVerifyTicketRsp) GetServerTime() int64 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

func (m *PB_AthVerifyTicketRsp) GetSheetStatus() uint32 {
	if m != nil && m.SheetStatus != nil {
		return *m.SheetStatus
	}
	return 0
}

func (m *PB_AthVerifyTicketRsp) GetUpdateType() int32 {
	if m != nil && m.UpdateType != nil {
		return *m.UpdateType
	}
	return 0
}

func (m *PB_AthVerifyTicketRsp) GetIpPool() *PB_EntryIpPool {
	if m != nil {
		return m.IpPool
	}
	return nil
}

func (m *PB_AthVerifyTicketRsp) GetIsPrivateCloud() int32 {
	if m != nil && m.IsPrivateCloud != nil {
		return *m.IsPrivateCloud
	}
	return 0
}

type PB_AthLogoutReq struct {
	// 	optional string domain_name = 1;	//	注销的域名。这个消息中客户端不用设置这个字段，后台交互使用(已废弃--2014-06-03)
	LoginAccount     *string           `protobuf:"bytes,2,opt,name=login_account,json=loginAccount" json:"login_account,omitempty"`
	Cdt              *PB_ClientDevType `protobuf:"varint,3,opt,name=cdt,enum=com.sangfor.moa.protobuf.PB_ClientDevType,def=0" json:"cdt,omitempty"`
	Did              *int64            `protobuf:"varint,4,opt,name=did" json:"did,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PB_AthLogoutReq) Reset()                    { *m = PB_AthLogoutReq{} }
func (m *PB_AthLogoutReq) String() string            { return proto.CompactTextString(m) }
func (*PB_AthLogoutReq) ProtoMessage()               {}
func (*PB_AthLogoutReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

const Default_PB_AthLogoutReq_Cdt PB_ClientDevType = PB_ClientDevType_PBCDT_ANDROID

func (m *PB_AthLogoutReq) GetLoginAccount() string {
	if m != nil && m.LoginAccount != nil {
		return *m.LoginAccount
	}
	return ""
}

func (m *PB_AthLogoutReq) GetCdt() PB_ClientDevType {
	if m != nil && m.Cdt != nil {
		return *m.Cdt
	}
	return Default_PB_AthLogoutReq_Cdt
}

func (m *PB_AthLogoutReq) GetDid() int64 {
	if m != nil && m.Did != nil {
		return *m.Did
	}
	return 0
}

type PB_AthLogoutRsp struct {
	Result           *int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PB_AthLogoutRsp) Reset()                    { *m = PB_AthLogoutRsp{} }
func (m *PB_AthLogoutRsp) String() string            { return proto.CompactTextString(m) }
func (*PB_AthLogoutRsp) ProtoMessage()               {}
func (*PB_AthLogoutRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *PB_AthLogoutRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type PB_AthGetPidsResult struct {
	LoginAccount     *string `protobuf:"bytes,1,req,name=login_account,json=loginAccount" json:"login_account,omitempty"`
	Pid              *int64  `protobuf:"varint,2,opt,name=pid" json:"pid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PB_AthGetPidsResult) Reset()                    { *m = PB_AthGetPidsResult{} }
func (m *PB_AthGetPidsResult) String() string            { return proto.CompactTextString(m) }
func (*PB_AthGetPidsResult) ProtoMessage()               {}
func (*PB_AthGetPidsResult) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *PB_AthGetPidsResult) GetLoginAccount() string {
	if m != nil && m.LoginAccount != nil {
		return *m.LoginAccount
	}
	return ""
}

func (m *PB_AthGetPidsResult) GetPid() int64 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

type PB_AthGetPidsReq struct {
	Did *int64 `protobuf:"varint,1,opt,name=did" json:"did,omitempty"`
	// optional string domain_name = 2;	//(已废弃--2014-06-03)
	LoginAccounts    []string `protobuf:"bytes,3,rep,name=login_accounts,json=loginAccounts" json:"login_accounts,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PB_AthGetPidsReq) Reset()                    { *m = PB_AthGetPidsReq{} }
func (m *PB_AthGetPidsReq) String() string            { return proto.CompactTextString(m) }
func (*PB_AthGetPidsReq) ProtoMessage()               {}
func (*PB_AthGetPidsReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *PB_AthGetPidsReq) GetDid() int64 {
	if m != nil && m.Did != nil {
		return *m.Did
	}
	return 0
}

func (m *PB_AthGetPidsReq) GetLoginAccounts() []string {
	if m != nil {
		return m.LoginAccounts
	}
	return nil
}

type PB_AthGetPidsRsp struct {
	Result           *int32                 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Results          []*PB_AthGetPidsResult `protobuf:"bytes,2,rep,name=results" json:"results,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *PB_AthGetPidsRsp) Reset()                    { *m = PB_AthGetPidsRsp{} }
func (m *PB_AthGetPidsRsp) String() string            { return proto.CompactTextString(m) }
func (*PB_AthGetPidsRsp) ProtoMessage()               {}
func (*PB_AthGetPidsRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *PB_AthGetPidsRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *PB_AthGetPidsRsp) GetResults() []*PB_AthGetPidsResult {
	if m != nil {
		return m.Results
	}
	return nil
}

// version update check
type PB_AthVersionUpdateReq struct {
	Cdt              *PB_ClientDevType `protobuf:"varint,1,opt,name=cdt,enum=com.sangfor.moa.protobuf.PB_ClientDevType,def=0" json:"cdt,omitempty"`
	ClientVersion    *string           `protobuf:"bytes,2,req,name=client_version,json=clientVersion" json:"client_version,omitempty"`
	ClientSystem     *string           `protobuf:"bytes,3,opt,name=client_system,json=clientSystem" json:"client_system,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PB_AthVersionUpdateReq) Reset()                    { *m = PB_AthVersionUpdateReq{} }
func (m *PB_AthVersionUpdateReq) String() string            { return proto.CompactTextString(m) }
func (*PB_AthVersionUpdateReq) ProtoMessage()               {}
func (*PB_AthVersionUpdateReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

const Default_PB_AthVersionUpdateReq_Cdt PB_ClientDevType = PB_ClientDevType_PBCDT_ANDROID

func (m *PB_AthVersionUpdateReq) GetCdt() PB_ClientDevType {
	if m != nil && m.Cdt != nil {
		return *m.Cdt
	}
	return Default_PB_AthVersionUpdateReq_Cdt
}

func (m *PB_AthVersionUpdateReq) GetClientVersion() string {
	if m != nil && m.ClientVersion != nil {
		return *m.ClientVersion
	}
	return ""
}

func (m *PB_AthVersionUpdateReq) GetClientSystem() string {
	if m != nil && m.ClientSystem != nil {
		return *m.ClientSystem
	}
	return ""
}

type PB_AthVersionUpdateRsp struct {
	Result           *int32   `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	LatestClientVer  *string  `protobuf:"bytes,2,opt,name=latest_client_ver,json=latestClientVer" json:"latest_client_ver,omitempty"`
	UpdateUrl        *string  `protobuf:"bytes,3,opt,name=update_url,json=updateUrl" json:"update_url,omitempty"`
	UpdateInfo       []string `protobuf:"bytes,4,rep,name=update_info,json=updateInfo" json:"update_info,omitempty"`
	UpdateType       *int32   `protobuf:"varint,5,opt,name=update_type,json=updateType" json:"update_type,omitempty"`
	ServerVersion    *string  `protobuf:"bytes,6,opt,name=server_version,json=serverVersion" json:"server_version,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PB_AthVersionUpdateRsp) Reset()                    { *m = PB_AthVersionUpdateRsp{} }
func (m *PB_AthVersionUpdateRsp) String() string            { return proto.CompactTextString(m) }
func (*PB_AthVersionUpdateRsp) ProtoMessage()               {}
func (*PB_AthVersionUpdateRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{21} }

func (m *PB_AthVersionUpdateRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *PB_AthVersionUpdateRsp) GetLatestClientVer() string {
	if m != nil && m.LatestClientVer != nil {
		return *m.LatestClientVer
	}
	return ""
}

func (m *PB_AthVersionUpdateRsp) GetUpdateUrl() string {
	if m != nil && m.UpdateUrl != nil {
		return *m.UpdateUrl
	}
	return ""
}

func (m *PB_AthVersionUpdateRsp) GetUpdateInfo() []string {
	if m != nil {
		return m.UpdateInfo
	}
	return nil
}

func (m *PB_AthVersionUpdateRsp) GetUpdateType() int32 {
	if m != nil && m.UpdateType != nil {
		return *m.UpdateType
	}
	return 0
}

func (m *PB_AthVersionUpdateRsp) GetServerVersion() string {
	if m != nil && m.ServerVersion != nil {
		return *m.ServerVersion
	}
	return ""
}

// WebStatusPush  status = 0 表示不在线 1 表示在线
type PB_AthWebStatusPush struct {
	Status           *PB_AthWebStatus `protobuf:"varint,1,req,name=status,enum=com.sangfor.moa.protobuf.PB_AthWebStatus" json:"status,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *PB_AthWebStatusPush) Reset()                    { *m = PB_AthWebStatusPush{} }
func (m *PB_AthWebStatusPush) String() string            { return proto.CompactTextString(m) }
func (*PB_AthWebStatusPush) ProtoMessage()               {}
func (*PB_AthWebStatusPush) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{22} }

func (m *PB_AthWebStatusPush) GetStatus() PB_AthWebStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return PB_AthWebStatus_AWS_OFFLINE
}

type PB_AthKickWebReq struct {
	Did              *int64 `protobuf:"varint,1,opt,name=did" json:"did,omitempty"`
	Pid              *int64 `protobuf:"varint,2,opt,name=pid" json:"pid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PB_AthKickWebReq) Reset()                    { *m = PB_AthKickWebReq{} }
func (m *PB_AthKickWebReq) String() string            { return proto.CompactTextString(m) }
func (*PB_AthKickWebReq) ProtoMessage()               {}
func (*PB_AthKickWebReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{23} }

func (m *PB_AthKickWebReq) GetDid() int64 {
	if m != nil && m.Did != nil {
		return *m.Did
	}
	return 0
}

func (m *PB_AthKickWebReq) GetPid() int64 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

type PB_AthKickWebRsp struct {
	Result           *int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PB_AthKickWebRsp) Reset()                    { *m = PB_AthKickWebRsp{} }
func (m *PB_AthKickWebRsp) String() string            { return proto.CompactTextString(m) }
func (*PB_AthKickWebRsp) ProtoMessage()               {}
func (*PB_AthKickWebRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{24} }

func (m *PB_AthKickWebRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 客户端活跃消息（没有应答，统计用户活跃度）
type PB_AthActiveMsg struct {
	Did              *int64 `protobuf:"varint,1,opt,name=did" json:"did,omitempty"`
	Pid              *int64 `protobuf:"varint,2,opt,name=pid" json:"pid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PB_AthActiveMsg) Reset()                    { *m = PB_AthActiveMsg{} }
func (m *PB_AthActiveMsg) String() string            { return proto.CompactTextString(m) }
func (*PB_AthActiveMsg) ProtoMessage()               {}
func (*PB_AthActiveMsg) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{25} }

func (m *PB_AthActiveMsg) GetDid() int64 {
	if m != nil && m.Did != nil {
		return *m.Did
	}
	return 0
}

func (m *PB_AthActiveMsg) GetPid() int64 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

// 校验密码，主要用于登陆后，或者其他地方来校验再次输入的密码
type PB_AthCheckPasswordReq struct {
	Did              *int64  `protobuf:"varint,1,opt,name=did" json:"did,omitempty"`
	Pid              *int64  `protobuf:"varint,2,opt,name=pid" json:"pid,omitempty"`
	Account          *string `protobuf:"bytes,4,opt,name=account" json:"account,omitempty"`
	Password         []byte  `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PB_AthCheckPasswordReq) Reset()                    { *m = PB_AthCheckPasswordReq{} }
func (m *PB_AthCheckPasswordReq) String() string            { return proto.CompactTextString(m) }
func (*PB_AthCheckPasswordReq) ProtoMessage()               {}
func (*PB_AthCheckPasswordReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{26} }

func (m *PB_AthCheckPasswordReq) GetDid() int64 {
	if m != nil && m.Did != nil {
		return *m.Did
	}
	return 0
}

func (m *PB_AthCheckPasswordReq) GetPid() int64 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

func (m *PB_AthCheckPasswordReq) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *PB_AthCheckPasswordReq) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

type PB_AthCheckPasswordRsp struct {
	Result           *int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Pid              *int64 `protobuf:"varint,2,opt,name=pid" json:"pid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PB_AthCheckPasswordRsp) Reset()                    { *m = PB_AthCheckPasswordRsp{} }
func (m *PB_AthCheckPasswordRsp) String() string            { return proto.CompactTextString(m) }
func (*PB_AthCheckPasswordRsp) ProtoMessage()               {}
func (*PB_AthCheckPasswordRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{27} }

func (m *PB_AthCheckPasswordRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *PB_AthCheckPasswordRsp) GetPid() int64 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

type PB_AthPwdForceModifyReq struct {
	Did              *int64 `protobuf:"varint,1,opt,name=did" json:"did,omitempty"`
	Pid              *int64 `protobuf:"varint,2,opt,name=pid" json:"pid,omitempty"`
	Password         []byte `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PB_AthPwdForceModifyReq) Reset()                    { *m = PB_AthPwdForceModifyReq{} }
func (m *PB_AthPwdForceModifyReq) String() string            { return proto.CompactTextString(m) }
func (*PB_AthPwdForceModifyReq) ProtoMessage()               {}
func (*PB_AthPwdForceModifyReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{28} }

func (m *PB_AthPwdForceModifyReq) GetDid() int64 {
	if m != nil && m.Did != nil {
		return *m.Did
	}
	return 0
}

func (m *PB_AthPwdForceModifyReq) GetPid() int64 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

func (m *PB_AthPwdForceModifyReq) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

type PB_AthPwdForceModifyRsp struct {
	Result           *int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PB_AthPwdForceModifyRsp) Reset()                    { *m = PB_AthPwdForceModifyRsp{} }
func (m *PB_AthPwdForceModifyRsp) String() string            { return proto.CompactTextString(m) }
func (*PB_AthPwdForceModifyRsp) ProtoMessage()               {}
func (*PB_AthPwdForceModifyRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{29} }

func (m *PB_AthPwdForceModifyRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 【发送验证码】
type PB_AthCaptchaSendReq struct {
	LoginAccount     *string `protobuf:"bytes,1,req,name=login_account,json=loginAccount" json:"login_account,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PB_AthCaptchaSendReq) Reset()                    { *m = PB_AthCaptchaSendReq{} }
func (m *PB_AthCaptchaSendReq) String() string            { return proto.CompactTextString(m) }
func (*PB_AthCaptchaSendReq) ProtoMessage()               {}
func (*PB_AthCaptchaSendReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{30} }

func (m *PB_AthCaptchaSendReq) GetLoginAccount() string {
	if m != nil && m.LoginAccount != nil {
		return *m.LoginAccount
	}
	return ""
}

type PB_AthCaptchaSendRsp struct {
	Result           *int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PB_AthCaptchaSendRsp) Reset()                    { *m = PB_AthCaptchaSendRsp{} }
func (m *PB_AthCaptchaSendRsp) String() string            { return proto.CompactTextString(m) }
func (*PB_AthCaptchaSendRsp) ProtoMessage()               {}
func (*PB_AthCaptchaSendRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{31} }

func (m *PB_AthCaptchaSendRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// /////////////////////////////////////////////////////////////////////////////
//  推送操作
// /////////////////////////////////////////////////////////////////////////////
type PB_AthCancelPush struct {
	Did              *int64            `protobuf:"varint,1,opt,name=did" json:"did,omitempty"`
	Pid              *int64            `protobuf:"varint,2,opt,name=pid" json:"pid,omitempty"`
	Reason           *int32            `protobuf:"varint,3,opt,name=reason" json:"reason,omitempty"`
	Cdt              *PB_ClientDevType `protobuf:"varint,4,opt,name=cdt,enum=com.sangfor.moa.protobuf.PB_ClientDevType,def=0" json:"cdt,omitempty"`
	CancelTime       *int64            `protobuf:"varint,5,opt,name=cancel_time,json=cancelTime" json:"cancel_time,omitempty"`
	LatestClientVer  *string           `protobuf:"bytes,6,opt,name=latest_client_ver,json=latestClientVer" json:"latest_client_ver,omitempty"`
	UpdateUrl        *string           `protobuf:"bytes,7,opt,name=update_url,json=updateUrl" json:"update_url,omitempty"`
	UpdateInfo       []string          `protobuf:"bytes,8,rep,name=update_info,json=updateInfo" json:"update_info,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *PB_AthCancelPush) Reset()                    { *m = PB_AthCancelPush{} }
func (m *PB_AthCancelPush) String() string            { return proto.CompactTextString(m) }
func (*PB_AthCancelPush) ProtoMessage()               {}
func (*PB_AthCancelPush) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{32} }

const Default_PB_AthCancelPush_Cdt PB_ClientDevType = PB_ClientDevType_PBCDT_ANDROID

func (m *PB_AthCancelPush) GetDid() int64 {
	if m != nil && m.Did != nil {
		return *m.Did
	}
	return 0
}

func (m *PB_AthCancelPush) GetPid() int64 {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return 0
}

func (m *PB_AthCancelPush) GetReason() int32 {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return 0
}

func (m *PB_AthCancelPush) GetCdt() PB_ClientDevType {
	if m != nil && m.Cdt != nil {
		return *m.Cdt
	}
	return Default_PB_AthCancelPush_Cdt
}

func (m *PB_AthCancelPush) GetCancelTime() int64 {
	if m != nil && m.CancelTime != nil {
		return *m.CancelTime
	}
	return 0
}

func (m *PB_AthCancelPush) GetLatestClientVer() string {
	if m != nil && m.LatestClientVer != nil {
		return *m.LatestClientVer
	}
	return ""
}

func (m *PB_AthCancelPush) GetUpdateUrl() string {
	if m != nil && m.UpdateUrl != nil {
		return *m.UpdateUrl
	}
	return ""
}

func (m *PB_AthCancelPush) GetUpdateInfo() []string {
	if m != nil {
		return m.UpdateInfo
	}
	return nil
}

type PB_AthVersionPush struct {
	ChangeType       *int64 `protobuf:"varint,1,opt,name=change_type,json=changeType" json:"change_type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PB_AthVersionPush) Reset()                    { *m = PB_AthVersionPush{} }
func (m *PB_AthVersionPush) String() string            { return proto.CompactTextString(m) }
func (*PB_AthVersionPush) ProtoMessage()               {}
func (*PB_AthVersionPush) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{33} }

func (m *PB_AthVersionPush) GetChangeType() int64 {
	if m != nil && m.ChangeType != nil {
		return *m.ChangeType
	}
	return 0
}

type PB_AthIpsPush struct {
	Ips              []string `protobuf:"bytes,1,rep,name=ips" json:"ips,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PB_AthIpsPush) Reset()                    { *m = PB_AthIpsPush{} }
func (m *PB_AthIpsPush) String() string            { return proto.CompactTextString(m) }
func (*PB_AthIpsPush) ProtoMessage()               {}
func (*PB_AthIpsPush) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{34} }

func (m *PB_AthIpsPush) GetIps() []string {
	if m != nil {
		return m.Ips
	}
	return nil
}

func init() {
	proto.RegisterType((*PB_EntryIp)(nil), "com.sangfor.moa.protobuf.PB_EntryIp")
	proto.RegisterType((*PB_EntryIpPool)(nil), "com.sangfor.moa.protobuf.PB_EntryIpPool")
	proto.RegisterType((*PB_AthLoginReq)(nil), "com.sangfor.moa.protobuf.PB_AthLoginReq")
	proto.RegisterType((*PB_AthLoginRsp)(nil), "com.sangfor.moa.protobuf.PB_AthLoginRsp")
	proto.RegisterType((*PB_AthAuthReq)(nil), "com.sangfor.moa.protobuf.PB_AthAuthReq")
	proto.RegisterType((*PB_AthAuthRsp)(nil), "com.sangfor.moa.protobuf.PB_AthAuthRsp")
	proto.RegisterType((*PB_AthAuthCaptchaReq)(nil), "com.sangfor.moa.protobuf.PB_AthAuthCaptchaReq")
	proto.RegisterType((*PB_AthAuthCaptchaRsp)(nil), "com.sangfor.moa.protobuf.PB_AthAuthCaptchaRsp")
	proto.RegisterType((*PB_AthFindPasswordReq)(nil), "com.sangfor.moa.protobuf.PB_AthFindPasswordReq")
	proto.RegisterType((*PB_AthFindPasswordDomainInfo)(nil), "com.sangfor.moa.protobuf.PB_AthFindPasswordDomainInfo")
	proto.RegisterType((*PB_AthFindPasswordRsp)(nil), "com.sangfor.moa.protobuf.PB_AthFindPasswordRsp")
	proto.RegisterType((*PB_AthModifyPasswordReq)(nil), "com.sangfor.moa.protobuf.PB_AthModifyPasswordReq")
	proto.RegisterType((*PB_AthModifyPasswordRsp)(nil), "com.sangfor.moa.protobuf.PB_AthModifyPasswordRsp")
	proto.RegisterType((*PB_AthVerifyTicketReq)(nil), "com.sangfor.moa.protobuf.PB_AthVerifyTicketReq")
	proto.RegisterType((*PB_AthVerifyTicketRsp)(nil), "com.sangfor.moa.protobuf.PB_AthVerifyTicketRsp")
	proto.RegisterType((*PB_AthLogoutReq)(nil), "com.sangfor.moa.protobuf.PB_AthLogoutReq")
	proto.RegisterType((*PB_AthLogoutRsp)(nil), "com.sangfor.moa.protobuf.PB_AthLogoutRsp")
	proto.RegisterType((*PB_AthGetPidsResult)(nil), "com.sangfor.moa.protobuf.PB_AthGetPidsResult")
	proto.RegisterType((*PB_AthGetPidsReq)(nil), "com.sangfor.moa.protobuf.PB_AthGetPidsReq")
	proto.RegisterType((*PB_AthGetPidsRsp)(nil), "com.sangfor.moa.protobuf.PB_AthGetPidsRsp")
	proto.RegisterType((*PB_AthVersionUpdateReq)(nil), "com.sangfor.moa.protobuf.PB_AthVersionUpdateReq")
	proto.RegisterType((*PB_AthVersionUpdateRsp)(nil), "com.sangfor.moa.protobuf.PB_AthVersionUpdateRsp")
	proto.RegisterType((*PB_AthWebStatusPush)(nil), "com.sangfor.moa.protobuf.PB_AthWebStatusPush")
	proto.RegisterType((*PB_AthKickWebReq)(nil), "com.sangfor.moa.protobuf.PB_AthKickWebReq")
	proto.RegisterType((*PB_AthKickWebRsp)(nil), "com.sangfor.moa.protobuf.PB_AthKickWebRsp")
	proto.RegisterType((*PB_AthActiveMsg)(nil), "com.sangfor.moa.protobuf.PB_AthActiveMsg")
	proto.RegisterType((*PB_AthCheckPasswordReq)(nil), "com.sangfor.moa.protobuf.PB_AthCheckPasswordReq")
	proto.RegisterType((*PB_AthCheckPasswordRsp)(nil), "com.sangfor.moa.protobuf.PB_AthCheckPasswordRsp")
	proto.RegisterType((*PB_AthPwdForceModifyReq)(nil), "com.sangfor.moa.protobuf.PB_AthPwdForceModifyReq")
	proto.RegisterType((*PB_AthPwdForceModifyRsp)(nil), "com.sangfor.moa.protobuf.PB_AthPwdForceModifyRsp")
	proto.RegisterType((*PB_AthCaptchaSendReq)(nil), "com.sangfor.moa.protobuf.PB_AthCaptchaSendReq")
	proto.RegisterType((*PB_AthCaptchaSendRsp)(nil), "com.sangfor.moa.protobuf.PB_AthCaptchaSendRsp")
	proto.RegisterType((*PB_AthCancelPush)(nil), "com.sangfor.moa.protobuf.PB_AthCancelPush")
	proto.RegisterType((*PB_AthVersionPush)(nil), "com.sangfor.moa.protobuf.PB_AthVersionPush")
	proto.RegisterType((*PB_AthIpsPush)(nil), "com.sangfor.moa.protobuf.PB_AthIpsPush")
	proto.RegisterEnum("com.sangfor.moa.protobuf.PB_EntryIpType", PB_EntryIpType_name, PB_EntryIpType_value)
	proto.RegisterEnum("com.sangfor.moa.protobuf.PB_AthAlgorithm", PB_AthAlgorithm_name, PB_AthAlgorithm_value)
	proto.RegisterEnum("com.sangfor.moa.protobuf.PB_AthUpdateType", PB_AthUpdateType_name, PB_AthUpdateType_value)
	proto.RegisterEnum("com.sangfor.moa.protobuf.PB_AthWebStatus", PB_AthWebStatus_name, PB_AthWebStatus_value)
	proto.RegisterEnum("com.sangfor.moa.protobuf.PB_AthVersionChange", PB_AthVersionChange_name, PB_AthVersionChange_value)
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1748 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xcd, 0x6e, 0xdb, 0xca,
	0x15, 0x0e, 0x49, 0xeb, 0xef, 0xe8, 0xc7, 0x32, 0x7d, 0x93, 0x12, 0xb9, 0x6d, 0xaf, 0xcd, 0xf6,
	0x02, 0xba, 0x06, 0x6a, 0xf4, 0x1a, 0x69, 0x16, 0xe9, 0x8a, 0x96, 0x64, 0x47, 0x88, 0x2d, 0x0b,
	0x94, 0xed, 0x34, 0x2b, 0x82, 0x26, 0xc7, 0xd2, 0x20, 0x14, 0xc9, 0x90, 0x94, 0x0d, 0x6f, 0x5b,
	0xa0, 0x8b, 0xee, 0x8a, 0xa0, 0x0f, 0xd0, 0x5d, 0x57, 0x05, 0xfa, 0x12, 0xdd, 0xf5, 0x2d, 0xfa,
	0x20, 0xc5, 0xfc, 0xe9, 0x87, 0xa4, 0x25, 0xa5, 0x31, 0xba, 0xea, 0x8e, 0x73, 0xc8, 0x99, 0x39,
	0x73, 0xbe, 0xef, 0x7c, 0xe7, 0x70, 0x00, 0xec, 0x69, 0x32, 0x3e, 0x0c, 0xa3, 0x20, 0x09, 0x54,
	0xcd, 0x09, 0x26, 0x87, 0xb1, 0xed, 0x8f, 0x6e, 0x83, 0xe8, 0x70, 0x12, 0xd8, 0xcc, 0x7c, 0x33,
	0xbd, 0x7d, 0x59, 0x73, 0x82, 0xc9, 0x24, 0xf0, 0x99, 0xe1, 0x65, 0xdd, 0x09, 0xfc, 0xc4, 0x76,
	0x12, 0x36, 0xd4, 0x7f, 0x0d, 0x30, 0x38, 0xb6, 0xba, 0x7e, 0x12, 0x3d, 0xf4, 0x42, 0x55, 0x85,
	0xad, 0xe4, 0x21, 0x44, 0x9a, 0xb4, 0x27, 0xb5, 0x0a, 0x26, 0x7d, 0x56, 0x1b, 0x20, 0xe3, 0x50,
	0x93, 0xf7, 0xa4, 0x56, 0xc5, 0x94, 0x71, 0xa8, 0xdf, 0x40, 0x63, 0x3e, 0x63, 0x10, 0x04, 0x9e,
	0xaa, 0x41, 0xe9, 0x0e, 0x45, 0x31, 0x0e, 0x7c, 0x3e, 0x51, 0x0c, 0xd5, 0xd7, 0xa0, 0xe0, 0x30,
	0xd6, 0xe4, 0x3d, 0xa5, 0x55, 0x3d, 0xfa, 0xe5, 0xe1, 0x63, 0x2e, 0x1e, 0xce, 0x17, 0x34, 0xc9,
	0x04, 0xfd, 0xb3, 0x42, 0x37, 0x31, 0x92, 0xf1, 0x59, 0x30, 0xc2, 0xbe, 0x89, 0x3e, 0xa9, 0xdf,
	0x41, 0xd5, 0x0d, 0x26, 0x36, 0xf6, 0x2d, 0xdf, 0x9e, 0x10, 0x0f, 0xe5, 0x56, 0xc5, 0x04, 0x66,
	0xea, 0xdb, 0x13, 0xa4, 0xfe, 0x02, 0xea, 0x1e, 0xf9, 0xd8, 0xb2, 0x1d, 0x27, 0x98, 0xfa, 0x89,
	0x26, 0xd3, 0x4f, 0x6a, 0xd4, 0x68, 0x30, 0x9b, 0xfa, 0x3d, 0x34, 0x1c, 0x0f, 0x23, 0x3f, 0xb1,
	0x84, 0xc7, 0x0a, 0xfd, 0xaa, 0xce, 0xac, 0xd7, 0xdc, 0xef, 0x77, 0xa0, 0x38, 0x6e, 0xa2, 0x6d,
	0xed, 0x49, 0xad, 0xc6, 0xd1, 0xc1, 0x4a, 0xbf, 0xdb, 0x74, 0x62, 0x07, 0xdd, 0x5d, 0x3e, 0x84,
	0xe8, 0x4d, 0x7d, 0x70, 0xdc, 0xee, 0x5c, 0x5a, 0x46, 0xbf, 0x63, 0x5e, 0xf4, 0x3a, 0x26, 0x59,
	0x45, 0x6d, 0x82, 0xe2, 0x62, 0x57, 0x2b, 0xec, 0x49, 0x2d, 0xc5, 0x24, 0x8f, 0xe4, 0x2c, 0x53,
	0x1f, 0x7f, 0x9a, 0x22, 0xcb, 0x09, 0x5c, 0xa4, 0x15, 0x69, 0x6c, 0x81, 0x99, 0xda, 0x81, 0x8b,
	0xe8, 0x61, 0xd1, 0x1d, 0x76, 0x90, 0x85, 0xfd, 0xdb, 0x40, 0x2b, 0xb1, 0x0f, 0x98, 0xa9, 0xe7,
	0xdf, 0x06, 0xea, 0xcf, 0xa1, 0x8a, 0x43, 0x2b, 0x0c, 0x02, 0x8f, 0x1c, 0x44, 0x2b, 0xd3, 0xb0,
	0x57, 0x30, 0xc5, 0xe3, 0x1a, 0x45, 0xea, 0x21, 0xec, 0xda, 0xbe, 0x1b, 0x05, 0xd8, 0xb5, 0xf8,
	0x4e, 0xb7, 0x9e, 0x3d, 0xd2, 0x2a, 0x74, 0xa1, 0x1d, 0xfe, 0xea, 0x8a, 0xbe, 0x39, 0xf1, 0xec,
	0x11, 0x09, 0x1e, 0x8f, 0x4b, 0xfc, 0x10, 0x27, 0x68, 0xa2, 0x01, 0xfd, 0xb2, 0xc6, 0x8c, 0x43,
	0x6a, 0xd3, 0xff, 0x99, 0x42, 0x25, 0x0e, 0xd5, 0x17, 0x50, 0x8c, 0x50, 0x3c, 0xf5, 0x12, 0x8e,
	0x3c, 0x1f, 0x91, 0x38, 0xc7, 0x28, 0xba, 0x43, 0xd1, 0x2c, 0xce, 0x8c, 0x40, 0x75, 0x66, 0x15,
	0x71, 0xfe, 0x16, 0x2a, 0x84, 0xc2, 0x56, 0x8c, 0x90, 0xab, 0x29, 0x7b, 0x52, 0xab, 0x66, 0x96,
	0x89, 0x61, 0x88, 0x90, 0xab, 0x0e, 0xf9, 0x4b, 0xdb, 0x1b, 0x05, 0x1c, 0x8a, 0x1f, 0x56, 0x42,
	0x61, 0x24, 0x63, 0xc3, 0x1b, 0x05, 0x11, 0x4e, 0xc6, 0x93, 0x37, 0xd5, 0xc1, 0xb1, 0x71, 0x76,
	0x7a, 0x61, 0xf5, 0x2f, 0xfa, 0x5d, 0xb6, 0x28, 0x79, 0xa7, 0x1e, 0xc0, 0x8e, 0x67, 0x27, 0x28,
	0x4e, 0xac, 0x39, 0x0f, 0x28, 0x34, 0x15, 0x73, 0x9b, 0xbd, 0x68, 0x0b, 0x26, 0xa8, 0x3f, 0x03,
	0x98, 0x86, 0xae, 0x9d, 0x20, 0x6b, 0x1a, 0x79, 0x1c, 0xa5, 0x0a, 0xb3, 0x5c, 0x45, 0x1e, 0x45,
	0x91, 0xbd, 0xe6, 0x20, 0x29, 0x14, 0x45, 0x6a, 0xa2, 0x20, 0x35, 0x19, 0xfb, 0xcb, 0xf4, 0x05,
	0x79, 0x5c, 0x98, 0x42, 0xd3, 0xac, 0x42, 0x63, 0xc6, 0xa7, 0x10, 0xfe, 0xa8, 0x06, 0x94, 0x38,
	0xae, 0x14, 0x81, 0xea, 0x51, 0x6b, 0x93, 0xa4, 0x21, 0xa8, 0x9b, 0x45, 0x86, 0xbe, 0xba, 0x0f,
	0x35, 0x1f, 0x21, 0xd7, 0x72, 0xec, 0x30, 0x71, 0xc6, 0xb6, 0x56, 0xa5, 0x9b, 0x54, 0x89, 0xad,
	0xcd, 0x4c, 0xfa, 0x1f, 0x25, 0xa8, 0xf3, 0x78, 0x4d, 0x93, 0x31, 0xc9, 0xae, 0x9c, 0xe4, 0x91,
	0x32, 0xc9, 0xb3, 0x0f, 0x35, 0xe4, 0x3b, 0xd1, 0x43, 0x98, 0x58, 0xae, 0x9d, 0xd8, 0x1c, 0xb0,
	0x2a, 0xb7, 0x75, 0xec, 0xc4, 0x16, 0x5c, 0xdf, 0x9a, 0x73, 0xfd, 0x5b, 0xa8, 0xdc, 0xa3, 0x1b,
	0xcb, 0x0f, 0x7c, 0x87, 0x31, 0xbd, 0x66, 0x96, 0xef, 0xd1, 0x4d, 0x9f, 0x8c, 0xf5, 0x3f, 0x29,
	0x4b, 0x8e, 0xac, 0x20, 0x14, 0x5f, 0x58, 0x9e, 0x2f, 0xdc, 0x04, 0x25, 0xc4, 0x8c, 0x35, 0x8a,
	0x49, 0x1e, 0xc9, 0xdc, 0x04, 0x3b, 0x1f, 0x11, 0x4b, 0xdc, 0x9a, 0xc9, 0x47, 0xea, 0x5b, 0x00,
	0xe2, 0x42, 0x9c, 0xd8, 0xc9, 0x34, 0xa6, 0x60, 0x6f, 0xc0, 0xa4, 0xf7, 0xe8, 0x66, 0x48, 0x27,
	0x98, 0xc4, 0x7f, 0xf6, 0x98, 0x16, 0x21, 0x9e, 0xb8, 0x0b, 0x22, 0xf4, 0x06, 0x0a, 0x21, 0x85,
	0xb6, 0x44, 0x77, 0x59, 0x2d, 0x79, 0x03, 0xec, 0x12, 0xd0, 0x4d, 0x36, 0x85, 0x2c, 0xce, 0x73,
	0x26, 0xc1, 0x13, 0x44, 0x73, 0x5a, 0x31, 0x81, 0x99, 0x2e, 0xf1, 0x04, 0x91, 0xf8, 0xc7, 0x63,
	0x84, 0x12, 0x71, 0x12, 0x42, 0x9f, 0xba, 0x59, 0xa5, 0x36, 0xee, 0x20, 0xa7, 0x1c, 0xcc, 0x29,
	0xd7, 0x82, 0x26, 0x8e, 0xad, 0x30, 0xc2, 0x77, 0x84, 0x76, 0x8e, 0x17, 0x4c, 0x5d, 0xad, 0x46,
	0x43, 0xdb, 0xc0, 0xf1, 0x80, 0x99, 0xdb, 0xc4, 0xaa, 0x5f, 0xc1, 0x37, 0x73, 0x2c, 0x38, 0x55,
	0x72, 0xb9, 0x21, 0xe5, 0x70, 0x43, 0x83, 0x92, 0x20, 0x1c, 0xa3, 0x8e, 0x18, 0xea, 0x7f, 0x56,
	0xf2, 0xd6, 0xfd, 0x3f, 0xd4, 0xff, 0x1b, 0xa8, 0xab, 0xb9, 0x50, 0xff, 0x4b, 0x82, 0xe7, 0xec,
	0xec, 0x27, 0xd8, 0x77, 0x07, 0x76, 0x1c, 0xdf, 0x07, 0x91, 0xfb, 0x08, 0xd8, 0xd9, 0x2a, 0x9a,
	0x45, 0x68, 0x01, 0x7e, 0x65, 0x09, 0x7e, 0x26, 0x47, 0xf7, 0x56, 0xc8, 0xf7, 0xe0, 0x78, 0x55,
	0x7d, 0x74, 0x2f, 0xb6, 0x4d, 0x97, 0xc3, 0x42, 0x5e, 0x39, 0xc4, 0xbe, 0x33, 0x53, 0xb4, 0x22,
	0x93, 0x4d, 0xec, 0x3b, 0x42, 0xd0, 0x7e, 0x2f, 0xc1, 0x4f, 0xb3, 0xe7, 0xe9, 0x50, 0xb0, 0x84,
	0x14, 0x13, 0x8f, 0xc9, 0x61, 0xb8, 0xc7, 0xdf, 0x40, 0xc1, 0xa5, 0xc8, 0x32, 0xba, 0xb2, 0x01,
	0x2d, 0x48, 0xee, 0x04, 0xfb, 0xd6, 0x9c, 0x6f, 0x65, 0x6a, 0x18, 0x60, 0x97, 0xd4, 0x03, 0xf6,
	0x92, 0xce, 0xdb, 0x62, 0xf5, 0x80, 0x5a, 0x08, 0x21, 0xf4, 0xcf, 0xf9, 0x41, 0x5d, 0xc1, 0xf4,
	0x01, 0x94, 0x18, 0xa1, 0x44, 0x8b, 0xf4, 0x7a, 0x1d, 0x55, 0xf3, 0x8f, 0x67, 0x8a, 0x65, 0x04,
	0x29, 0x94, 0x19, 0x29, 0xf4, 0x3f, 0x48, 0xf0, 0x13, 0x36, 0xf7, 0x3c, 0x70, 0xf1, 0xed, 0xc3,
	0x22, 0xd8, 0xb3, 0xa8, 0xa4, 0x33, 0x4d, 0x9e, 0x67, 0xda, 0x3e, 0xd4, 0x02, 0xcf, 0x9d, 0xe3,
	0x47, 0xfa, 0xa5, 0x9a, 0x59, 0x0d, 0xbc, 0x99, 0x1f, 0x39, 0x10, 0xcb, 0x29, 0x88, 0xf5, 0x1f,
	0x1f, 0x71, 0xe2, 0xf1, 0xe0, 0xe8, 0x7f, 0x55, 0x44, 0x38, 0xaf, 0x51, 0x84, 0x6f, 0x1f, 0x2e,
	0x69, 0x86, 0x2f, 0xb9, 0x2d, 0x67, 0xdc, 0x96, 0x85, 0xdb, 0xbc, 0x83, 0x53, 0x9e, 0xa4, 0x83,
	0x5b, 0x54, 0x1b, 0x79, 0x41, 0x6d, 0xb2, 0xdd, 0x24, 0xe3, 0x6e, 0xaa, 0x9b, 0x4c, 0xd7, 0xcd,
	0x62, 0xb6, 0x6e, 0xa6, 0x52, 0xa0, 0xb4, 0xae, 0x23, 0x2c, 0xaf, 0xeb, 0x08, 0x2b, 0x1b, 0x76,
	0x84, 0xb0, 0x71, 0x47, 0x58, 0xcd, 0xe9, 0x08, 0xff, 0x5e, 0xc8, 0xc5, 0xe8, 0x2b, 0xc5, 0x3d,
	0x25, 0xbd, 0x5b, 0x19, 0xe9, 0xcd, 0x88, 0x54, 0x21, 0xa7, 0x22, 0xcd, 0x41, 0x2b, 0x2e, 0x95,
	0x88, 0xdc, 0x0e, 0xb0, 0xb4, 0x49, 0x07, 0x58, 0x5e, 0xd3, 0x01, 0x56, 0x32, 0x1d, 0xe0, 0x72,
	0x39, 0x82, 0xaf, 0x28, 0x47, 0xb3, 0x6a, 0x53, 0xfd, 0xf2, 0x6a, 0x93, 0x6d, 0xc6, 0x6b, 0x79,
	0xcd, 0x38, 0xd7, 0x8e, 0xfa, 0x52, 0xbb, 0xba, 0x58, 0xa6, 0x1a, 0x6b, 0xcb, 0xd4, 0x76, 0xb6,
	0x4c, 0xa5, 0x5a, 0xde, 0xe6, 0xaa, 0x96, 0x77, 0xe7, 0xbf, 0x6c, 0x79, 0xf3, 0x0a, 0x9f, 0x9a,
	0x5b, 0xf8, 0xfe, 0x22, 0xc1, 0xf6, 0xec, 0x17, 0x26, 0x98, 0x26, 0x1b, 0xf7, 0xbe, 0x4f, 0xaa,
	0x27, 0x99, 0x2e, 0x59, 0xff, 0x21, 0xe5, 0xd6, 0x0a, 0x5d, 0x3c, 0x83, 0x5d, 0xf6, 0xe9, 0x29,
	0x4a, 0x06, 0xd8, 0x8d, 0x4d, 0x96, 0x58, 0x9b, 0x16, 0xee, 0x65, 0x79, 0xd7, 0xdf, 0x41, 0x33,
	0xb5, 0x5a, 0x5e, 0x59, 0xf8, 0x1e, 0x1a, 0x4b, 0x8b, 0x8b, 0x0a, 0x53, 0x5f, 0x5c, 0x3d, 0xd6,
	0xe3, 0xf4, 0x62, 0x2b, 0x84, 0xe0, 0x14, 0x4a, 0xec, 0x49, 0xd4, 0xbe, 0x5f, 0xad, 0xcb, 0x8b,
	0xa5, 0xf3, 0x9a, 0x62, 0xb6, 0xfe, 0x0f, 0x09, 0x5e, 0xcc, 0x34, 0x88, 0x10, 0xf9, 0x8a, 0x72,
	0x8b, 0x1c, 0x84, 0x83, 0x26, 0x3d, 0x09, 0x68, 0x59, 0xb1, 0x97, 0xf3, 0xae, 0x0e, 0x32, 0xba,
	0xa9, 0xe4, 0xe8, 0xe6, 0xbf, 0x1f, 0xf1, 0x39, 0x15, 0x2f, 0x79, 0x21, 0x5e, 0xb9, 0xb2, 0x25,
	0x6f, 0x22, 0x5b, 0xca, 0x1a, 0xd9, 0xda, 0xca, 0xc8, 0x56, 0x2a, 0x67, 0x0b, 0x99, 0x9c, 0xcd,
	0x2a, 0x4a, 0x31, 0x47, 0x51, 0xf4, 0xdf, 0x09, 0xaa, 0xce, 0x24, 0x6d, 0x30, 0x8d, 0xc7, 0xaa,
	0x01, 0x45, 0xae, 0x17, 0xe4, 0x88, 0x5f, 0xa4, 0x88, 0x7c, 0xa2, 0xfe, 0x5a, 0x30, 0xed, 0x1d,
	0x76, 0x3e, 0xbe, 0x47, 0x37, 0x1b, 0x76, 0x33, 0xfa, 0x41, 0x7a, 0xde, 0x8a, 0x44, 0xfb, 0x8d,
	0xc8, 0x49, 0xc3, 0x49, 0xf0, 0x1d, 0x3a, 0x8f, 0x47, 0x1b, 0x6d, 0x11, 0x09, 0x68, 0xdb, 0x63,
	0xe4, 0x7c, 0xfc, 0xd2, 0x76, 0x4b, 0x83, 0x92, 0x48, 0x60, 0x56, 0xf7, 0xc4, 0x50, 0x7d, 0x09,
	0xe5, 0x85, 0x26, 0x8c, 0xfe, 0x47, 0x8b, 0xb1, 0x7e, 0x9c, 0xbf, 0xe7, 0xea, 0x3a, 0x9c, 0xf2,
	0xfb, 0x83, 0x68, 0xd1, 0x06, 0xf7, 0xee, 0x49, 0x10, 0x39, 0x88, 0xb5, 0x6a, 0x9b, 0x3a, 0xbe,
	0xca, 0xbd, 0x1f, 0x1f, 0x59, 0x7a, 0x45, 0xf0, 0x7f, 0x2b, 0x7e, 0x1a, 0x79, 0x8b, 0x3f, 0x44,
	0xfe, 0xc6, 0xff, 0x27, 0xfa, 0x61, 0xde, 0xe4, 0x15, 0x9b, 0xfd, 0x4d, 0x16, 0xb4, 0x68, 0xdb,
	0xbe, 0x83, 0x3c, 0xca, 0xd2, 0x4d, 0x0e, 0x4d, 0x17, 0xb4, 0x63, 0x7a, 0x8d, 0xc8, 0x17, 0x24,
	0xa3, 0xa7, 0xbd, 0x3f, 0xfc, 0x0e, 0xaa, 0x0e, 0x75, 0x8b, 0x55, 0x61, 0x76, 0x8f, 0x08, 0xcc,
	0x44, 0xab, 0x70, 0xae, 0x34, 0x14, 0x37, 0x91, 0x86, 0xd2, 0x1a, 0x69, 0x28, 0xa7, 0xa5, 0x41,
	0x7f, 0x05, 0x3b, 0x4b, 0xc2, 0x45, 0x43, 0x45, 0x3c, 0x1c, 0xdb, 0xfe, 0x88, 0xeb, 0x85, 0xc4,
	0x3d, 0xa4, 0x26, 0x72, 0x2c, 0x7d, 0x5f, 0x5c, 0xf3, 0xf4, 0xc2, 0x58, 0x04, 0x97, 0xf4, 0x1a,
	0xd2, 0xac, 0xd7, 0x38, 0x78, 0xb5, 0x78, 0xad, 0x4c, 0x45, 0xa6, 0x09, 0xb5, 0xc1, 0x71, 0xb7,
	0x77, 0x69, 0x0d, 0xbb, 0xed, 0x8b, 0x7e, 0xa7, 0xf9, 0x6c, 0x6e, 0x39, 0x37, 0x86, 0x97, 0x5d,
	0xb3, 0x29, 0x1d, 0x1c, 0xcd, 0x72, 0x54, 0x5c, 0xfc, 0xa9, 0xdb, 0xb0, 0x78, 0xf5, 0xd7, 0x7c,
	0xa6, 0x36, 0x00, 0xb8, 0xc1, 0xe8, 0x0e, 0x9b, 0xd2, 0x81, 0x21, 0xc0, 0xbe, 0x9a, 0x0b, 0xda,
	0x73, 0x72, 0xac, 0xab, 0x41, 0xc7, 0xb8, 0xec, 0x5a, 0x17, 0x66, 0xa7, 0xd7, 0x37, 0xcc, 0x0f,
	0xcd, 0x67, 0xea, 0x0b, 0x50, 0x67, 0xe6, 0xee, 0x79, 0xd7, 0x3c, 0xed, 0xf6, 0xdb, 0x1f, 0x16,
	0xb7, 0x9d, 0x29, 0x13, 0xd9, 0xd6, 0x78, 0x3f, 0xb4, 0x2e, 0x4e, 0x4e, 0xce, 0x7a, 0x62, 0x5b,
	0x6a, 0xe8, 0xd3, 0x31, 0xd9, 0x76, 0x77, 0x29, 0x72, 0x6d, 0x1a, 0x1e, 0x75, 0x17, 0xb6, 0xaf,
	0xbb, 0xe6, 0xb0, 0x77, 0xd1, 0xb7, 0xda, 0x6f, 0x8d, 0xfe, 0x69, 0x97, 0x1c, 0xf4, 0x39, 0xec,
	0x08, 0xe3, 0x55, 0x5f, 0x98, 0xa5, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x7b, 0xf2, 0x98,
	0xf0, 0x17, 0x00, 0x00,
}
